### PR TITLE
Add rkt service templates depending on the version

### PR DESCRIPTION
**Pull request by hectorj2f**
We should add the rkt that differ based on the rkt version:
 - rkt-metadata
- rkt-gc

### CODE REVIEW

**Comment by teemow** [comment]
@hectorj2f I've updated the PR with my changes.

**Comment by hectorj2f** [comment]
Thanks @teemow, I'll have a look at them

**Comment by hectorj2f** [comment]
@teemow code LGTM although I couldn't test it yet

**Comment by teemow** [comment]
I've tested it with Onsho. Looks good.

**Pull request merged**
