### PR TITLE
 Adapt to docker template to the version

### PR DESCRIPTION
**Pull request by hectorj2f**
I added a function to compare versions and tests for the docker template and the version function.

ping @teemow

### CODE REVIEW

**Comment by teemow** [comment]
This fixes #10 and https://github.com/giantswarm/provisioner/pull/29

But the croups driver switch is afaik only necessary with systemd 226+. Which also means that <docker 1.9 does not work with >=systemd 226. 

Currently we don't track the systemd version with yochu but this should be easy to figure out.

**Comment by hectorj2f** [comment]
@teemow okay, let's address it in a different PR.

**Comment by teemow** [comment]
@hectorj2f I've tested this branch against 

Docker 1.6.2, 1.9.1, 1.10.1
Systemd 222, 226, 229

All combinations worked perfectly. So no worries. 

LGTM and WFM!

**Comment by hectorj2f** [comment]
@teemow thx! :)

**Pull request merged**
