### PR TITLE
Fix daemon command for docker 1.10

### PR DESCRIPTION
**Pull request by teemow**
change docker daemon cmd from '-d' to 'daemon'

### CODE REVIEW

**Comment by hectorj2f** [comment]
LGTM

**Comment by hectorj2f** [comment]
Is it ready to review @teemow ? I saw the tag `wip` afterwards :)

**Comment by teemow** [comment]
I think it will be better to have a conditional based on the docker version in here. So it works with old and new versions. 

There have been modifications for docker 1.9 as well that haven't yet made it into Yochu.

See https://github.com/giantswarm/provisioner/pull/29

**Comment by hectorj2f** [comment]
Yes, we could use the text templates to check whether the version is greater or lower than... always considering it a number.

**Comment by teemow** [comment]
We should also use a newer unit definition (Type=notify!). 

https://github.com/docker/docker/blob/master/contrib/init/systemd/docker.service#L8

**Comment by hectorj2f** [comment]
@teemow I'd try to do something with the templates and send a PR to your branch

**Comment by hectorj2f** [comment]
LGTM

**Pull request merged**
